### ISSUE TITLE
Add a listener to location changes to routing also adds the reply button

### ISSUE THREAD

**Issue by rodrigo-picanco** [pmqueiroz/basecamp-replier#1]
Thank you for this amazing extension btw! 

I was wondering if we could place a listener on route changes so the message reply button is added when you navigate trough basecamp. 

Is it possible?

**Comment by pmqueiroz** [comment]
That's one of our [todos](https://github.com/pmqueiroz/basecamp-replier#Todo-Features). I assure you Im searching how can i easily make this feat possible
